server:
  port: 8200
spring:
  application:
    name: travel-gateway-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: true
  routes:
    user:
      path: /user/**
      serviceId: travel-user-service
    picture:
      path: /picture/**
      serviceId: travel-picture-service
    sms:
      path: /sms/**
      serviceId: travel-sms-service
    spot:
      path: /spot/**
      serviceId: travel-spot-service
    moment:
      path: /moment/**
      serviceId: travel-moment-service
    topic:
      path: /topic/**
      serviceId: travel-topic-service
    cr:
      path: /cr/**
      serviceId: travel-cr-service
    qa:
      path: /qa/**
      serviceId: travel-qa-service
    thumbUp:
      path: /thumbUp/**
      serviceId: travel-thumbUp-service
    authorize:
      path: /authorize/**
      serviceId: travel-oauth2-service
    collect:
      path: /collect/**
      serviceId: travel-collect-service
  sensitive-headers:
  retryable: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000


#security:
#  oauth2:
#    client:
#      client-id: travel-gateway-service
#      client-secret: 123456
#    resource:
#      jwt:
#        key-uri: http://127.0.0.1:8300/oauth/token_key

