server:
  port: 8107
spring:
  application:
    name: travel-moment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/travel?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.zhiming.travel.moment.domain
  configuration:
    map-underscore-to-camel-case: true
travel:
  service:
    serviceId: 7
    machineId: 1
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
