server:
  port: 8103
spring:
  application:
    name: travel-sms-service
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
jiguang:
  appKey: "9dfcd6b12a2b09e840e0483c"
  masterSecret: "11e47109b5a6c6181f5e9d28"
