server:
  port: 8104
spring:
  application:
    name: travel-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/travel?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.zhiming.travel.user.domain
  configuration:
    map-underscore-to-camel-case: true
travel:
  service:
    serviceId: 4
    machineId: 1
  user:
    defaultAvatar: "http://www.baidu.com"
    defaultBackground: "http://www.baidu.com"

